# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
before_install:
- rvm install ruby-2.2.2
- gem install cocoapods
- gem install xcpretty -N
- gem install xcpretty-travis-formatter
- pod repo update
- pod install --project-directory=Example
podfile: Example/Podfile
script:
- set -o pipefail && xcodebuild -enableCodeCoverage YES -workspace Example/FunkyNetwork.xcworkspace -scheme FunkyNetwork-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.0' -sdk iphonesimulator12.0 clean build test ONLY_ACTIVE_ARCH=NO | xcpretty  -f `xcpretty-travis-formatter`
